POST https://d1442-api.103.74.254.185.nip.io/createlink
Content-Type: application/json

{
  "phonenumber" : "0828955697",
  "sms" : false,
  "agent" : "9401",
  "province_id" : "27",
  "conference" : "false",
  "ippbx_id" : "IPPBX1.166927.1599625992.2400",
  "type" : "webrtc"
}
